name: Deploy To S3

on:
  push:
    branches: [dev-fe]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      working-directory: ./client

    steps:
      - name: checkout v2
        uses: actions/checkout@v2

      - name: Install Dependence
        run: npm install
        working-directory: ${{ env.working-directory }}

      - name: Build app
        run: npm run build
        working-directory: ${{ env.working-directory }}

      - name: Deploy To s3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            build s3://project-teatime-dev
